### ISSUE TITLE
EyeLink configuration settings update / fixes

### ISSUE THREAD

**Issue by isolver** [isolver/ioHub#72]
- [x] **enable_interface_without_connection:**
  - True,  == setting the eyelink library to use 'dummy mode' as SRR terms it. When a a can to setConnectionState(True) is made, the core eyelink DLL is opened without making an actual connection to the eye tracker. Tracker methods can be called but no data will be received by ioHub. Can be used to test experiment logic / graphics when a physical eyelink device is not available.
  - False == connect to the EyeLink Host, using default IP address, or that specified in the "network_settings" parameter.

**Comment by isolver** [comment]
- [x] **bug** track_eyes parameter not working. 
- [x] **bug** sample filter level switching file_filter and online_filter settings

**Comment by isolver** [comment]
- [x] **bug** tracking_mode ( pupil vs. pupil-cr ) only works if the setting is enabled in the Host App GUI.

**Comment by isolver** [comment]
All issues fixed.
